// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditStageDto } from "./AuditStageDto";

export type AuditRecordDto = { id: string, kind: string, 
/**
 * Run parameters (arbitrary JSON shape per kind).
 */
params: unknown, started_at: string, ended_at: string, duration_ms: number, stages: Array<AuditStageDto>, files: Array<string>, status: string, error: string | null, result_summary: string | null, artifact: string | null, };
