// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FetchSpecDto } from "./FetchSpecDto";

/**
 * 回测运行配置(留档 config.json 原文;Deserialize 供读回与重跑)。
 */
export type BacktestConfigDto = { 
/**
 * 工作区相对路径(examples/.. 或 deploy/..)。
 */
tree_path: string, 
/**
 * 主行情 CSV(工作区相对)。fetch 置时由任务先拉取生成。
 */
primary_path: string, 
/**
 * "sim_hard" | "sim_soft" | "score_hard" | "score_soft"
 */
mode: string, cost_bps: number, warmup: number, window: number, 
/**
 * 展示层初始资金(元);默认 100000。引擎 nav 语义不感知此值。
 */
initial_capital: number, 
/**
 * 可选:运行前刷新行情。
 */
fetch: FetchSpecDto | null, };
