// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BarDto = { t: string, open: number, high: number, low: number, close: number, volume: number, };
