// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendFoldDto } from "./BlendFoldDto";
import type { BlendFoldMeanDto } from "./BlendFoldMeanDto";

export type BlendDto = { folds: Array<BlendFoldDto>, mean: BlendFoldMeanDto, };
