// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlendFoldDto = { oos: string, corr: number, sh_ridge: number, sh_val: number, sh_blend: number, dd_ridge: number, dd_val: number, dd_blend: number, ex_ridge: number, ex_val: number, ex_blend: number, };
