// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalBriefDto } from "./SignalBriefDto";

export type BookCardDto = { 
/**
 * "b1" | "b2" | "b3"
 */
book: string, title: string, 
/**
 * "single" | "portfolio"
 */
kind: string, 
/**
 * "ok" | "empty"(state 未建) | "corrupt"(state 损坏/串树)
 */
status: string, 
/**
 * status != ok 时的可操作建议。
 */
advice: string | null, 
/**
 * 以下来自已 commit 的 state(empty/corrupt 时 None)。
 */
nav: number | null, total_return: number | null, max_drawdown: number | null, pos: number | null, state_time: string | null, 
/**
 * 账本3:当前持仓清单(symbol, weight)。
 */
holdings: Array<[string, number]> | null, 
/**
 * 最新信号(来自 sig_*.json;时间戳可能比 state 新——dry 残留,如实分开展示)。
 */
last_signal: SignalBriefDto | null, };
