// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookCardDto } from "./BookCardDto";
import type { JournalPointDto } from "./JournalPointDto";
import type { SnapshotDto } from "./SnapshotDto";

export type BookDetailDto = { card: BookCardDto, snapshot: SnapshotDto | null, journal: Array<JournalPointDto>, };
