// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CsvInfoDto = { 
/**
 * 工作区相对路径。
 */
path: string, 
/**
 * 解析失败→None(坏文件如实列出)。
 */
rows: number | null, first_t: string | null, last_t: string | null, };
