// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeployMonthRecDto = { as_of: string, nav: number, excess: number, n_holdings: number, n_buy: number, n_sell: number, };
