// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeployHoldingDto } from "./DeployHoldingDto";
import type { DeployMonthRecDto } from "./DeployMonthRecDto";
import type { DeployNavPointDto } from "./DeployNavPointDto";

export type DeployBookDto = { status: string, nav: number | null, excess_total: number | null, last_rebalance: string | null, holdings: Array<DeployHoldingDto>, nav_history: Array<DeployNavPointDto>, months: Array<DeployMonthRecDto>, };
