// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityRowDto } from "./CapacityRowDto";

export type DeployDto = { lag0_excess: number, lag1_excess: number, drag: number, adv_median: number, capacity: Array<CapacityRowDto>, };
