// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeployHoldingDto } from "./DeployHoldingDto";
import type { DiffRowDto } from "./DiffRowDto";

export type DeployMonthDto = { as_of: string, picks: Array<DeployHoldingDto>, diff: Array<DiffRowDto>, proj_nav: number, proj_excess: number, realized_ret: number, };
