// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffRowDto = { symbol: string, 
/**
 * "Buy" | "Sell" | "Adjust" | "Hold"
 */
action: string, from_w: number, to_w: number, };
