// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecayPointDto } from "./DecayPointDto";
import type { LayerStatsDto } from "./LayerStatsDto";

export type FactorStatsDto = { name: string, expr: string, n_periods: number, ic_mean: number | null, icir: number | null, ic_t: number | null, ic_pos_share: number | null, rank_ic_mean: number | null, rank_icir: number | null, ic_decay: Array<DecayPointDto>, layers: LayerStatsDto | null, };
