// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorrDto } from "./CorrDto";
import type { FactorStatsDto } from "./FactorStatsDto";

export type FactorReportDto = { n_symbols: number, sample: number, horizon: number, layers_q: number, factors: Array<FactorStatsDto>, corr: CorrDto | null, };
