// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FactorValueDto = { name: string, 
/**
 * 非有限→None(NaN 弃权语义如实呈现)。
 */
value: number | null, };
