// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FetchSpecDto = { symbol: string, 
/**
 * 分钟:15/60;日线:240。
 */
scale: number, datalen: number, 
/**
 * "qfq" | "none"
 */
adjust: string, };
