// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GateDto = { 
/**
 * "allow" | "dry_only" | "warn"
 */
gate: string, message: string | null, };
