// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GmTailConfig } from "./GmTailConfig";
import type { SchtaskDto } from "./SchtaskDto";

/**
 * 驾驶舱状态:任务是否装、schtasks 查询、配置、token 是否就绪、产物计数、日志尾。
 */
export type GmTailStatusDto = { installed: boolean, schtask: SchtaskDto | null, config: GmTailConfig, 
/**
 * data/gm/.token 存在且非空。
 */
token_present: boolean, 
/**
 * data/gm/k15m/*.csv 数量。
 */
k15m_count: number, 
/**
 * 最新 snapshot_*.csv 文件名。
 */
last_snapshot: string | null, 
/**
 * tail.log 末尾若干行。
 */
log_tail: Array<string>, };
