// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 尾盘漏斗 + 排程配置。launcher 读它构造 Python tail --funnel 参数。
 */
export type GmTailConfig = { 
/**
 * 触发时刻 "HH:MM"(24h)。默认 14:46——等 14:45 bar 落定。
 */
schedule_time: string, 
/**
 * 粗排键:liquidity|intraday|range_pos|vwap_gap。
 */
rank: string, 
/**
 * 短名单取前 N。
 */
top: number, 
/**
 * 日线候选集文件(""=不用;相对仓库根或绝对)。
 */
pool: string, 
/**
 * 门槛:今日成交额下限(元)。
 */
min_amount: number, 
/**
 * 门槛:最低价。
 */
min_price: number, 
/**
 * 门槛:剔除涨停封板(无卖盘)。
 */
drop_limit_up: boolean, };
