// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExcessPointDto } from "./ExcessPointDto";
import type { RegimeExcessDto } from "./RegimeExcessDto";

export type IndexRelativeDto = { benchmark: string, excess_cum: number | null, curve: Array<ExcessPointDto>, per_regime: Array<RegimeExcessDto>, };
