// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JournalPointDto = { state_time: string, nav: number | null, pos: number | null, 
/**
 * 账本3:成员数。
 */
members: number | null, };
