// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayerStatsDto = { q: number, ann_returns: Array<number | null>, spread_total: number, spread_sharpe: number | null, monotonicity: number | null, };
