// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OptimizeReportInfoDto = { path: string, name: string | null, mode: string | null, n_combos: number | null, folds: number | null, error: string | null, };
