// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookCardDto } from "./BookCardDto";
import type { DiffRowDto } from "./DiffRowDto";
import type { RunlogStatusDto } from "./RunlogStatusDto";
import type { SchtaskDto } from "./SchtaskDto";

export type OverviewDto = { cards: Array<BookCardDto>, 
/**
 * 账本3 今日清单 diff(来自 sig_portfolio.json trades)。
 */
diff: Array<DiffRowDto>, diff_t: string | null, runlog: RunlogStatusDto, 
/**
 * schtasks 查询失败/任务不存在 → None。
 */
schtask: SchtaskDto | null, 
/**
 * gm 尾盘取数计划任务(rquant-gm-tail)状态;未装/查询失败 → None。
 */
gm_tail: SchtaskDto | null, };
