// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactorKVDto } from "./FactorKVDto";

export type PaperStockDetailDto = { symbol: string, name: string, kday_path: string, asof: string, factors: Array<FactorKVDto>, };
