// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaperRowDto = { date: string, status: string, picks: Array<string>, turnover: number | null, gross_ret: number | null, net_ret: number | null, nav: number, };
