// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QualityLayerDto = { layer: number, n: number, mean_quality: number, mean_fwd_return: number, };
