// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegimeSliceDto = { label: string, from: string, to: string, picks_return: number, benchmark_return: number, excess: number, };
