// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplayStepDto } from "./ReplayStepDto";

export type ReplayFrameDto = { t: string, leaf: string, stance: string, path: Array<ReplayStepDto>, 
/**
 * sim 模式由 SimStepRecord 对齐补充;score 模式 None。
 */
target: number | null, pos: number | null, nav: number | null, };
