// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReplayStepDto = { node_id: string, label: string, confidence: number, rationale: string, };
