// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateDto } from "./GateDto";
import type { Tier2CellDto } from "./Tier2CellDto";

export type RoundCardDto = { round: bigint, label: string, benchmark: string, rebalance: bigint, verdict: string, gates: Array<GateDto>, tier2: Array<Tier2CellDto>, flags: Array<string>, config_path: string, };
