// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundGateDto } from "./RoundGateDto";
import type { Tier2CellDto } from "./Tier2CellDto";

export type RoundCardDto = { round: number, label: string, benchmark: string, rebalance: number, verdict: string, gates: Array<RoundGateDto>, tier2: Array<Tier2CellDto>, flags: Array<string>, config_path: string, };
