// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoundGateDto = { name: string, pass: boolean, value: number | null, threshold: number | null, note: string, };
