// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunlogStatusDto = { 
/**
 * 最近一段 run 的头行(==== 日期 ====)。
 */
last_header: string | null, 
/**
 * true=最近段含 committed/DRY 正常收尾;false=可疑(含 error 等);None=无日志。
 */
ok: boolean | null, summary: string, };
