// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 留档条目(meta.json;Deserialize 供列表读回)。
 */
export type RunMetaDto = { id: string, 
/**
 * 同 BacktestConfigDto.mode。
 */
kind: string, 
/**
 * 用户可改名;默认 "<树名> × <primary 文件名>"。
 */
name: string, tree_name: string, created: string, ok: boolean, error: string | null, };
