// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestConfigDto } from "./BacktestConfigDto";
import type { RunMetaDto } from "./RunMetaDto";

/**
 * 概览指标卡(sim 全量;score 仅 kind/tree_name + raw)。
 */
export type RunSummaryDto = { meta: RunMetaDto, config: BacktestConfigDto, total_return: number | null, max_drawdown: number | null, n_round_trips: number | null, win_rate: number | null, avg_hold_bars: number | null, turnover: number | null, buy_and_hold: number | null, sharpe: number | null, 
/**
 * 资金换算(严格口径):initial_capital×(1+total_return) / ×total_return。
 */
final_equity: number | null, net_pnl: number | null, 
/**
 * score 模式:result.json 原样(UI 原始视图/简版概览用)。sim 模式 None。
 */
raw: unknown, };
