// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SchtaskDto = { next_run: string | null, last_run: string | null, last_result: string | null, status: string | null, };
