// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenReasonDto } from "./ScreenReasonDto";

export type ScreenPickDto = { rank: number, symbol: string, quality_score: number, speculative_score: number, combined_score: number, tags: Array<string>, selected: boolean, reasons: Array<ScreenReasonDto>, };
