// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenPickDto } from "./ScreenPickDto";

export type ScreenResultDto = { config: string, as_of: string, n_universe: number, top: number, rows: Array<ScreenPickDto>, };
