// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavPointDto } from "./NavPointDto";
import type { QualityLayerDto } from "./QualityLayerDto";
import type { RegimeSliceDto } from "./RegimeSliceDto";
import type { ScreenRunMetaDto } from "./ScreenRunMetaDto";
import type { TagAttribDto } from "./TagAttribDto";

export type ScreenBacktestReportDto = { meta: ScreenRunMetaDto, net_total_return: number, gross_total_return: number, abs_sharpe: number | null, max_drawdown: number, turnover: number, break_even: number | null, nav: Array<NavPointDto>, tag_attribution: Array<TagAttribDto>, regime_slices: Array<RegimeSliceDto>, quality_layers: Array<QualityLayerDto>, };
