// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScreenRunMetaDto = { id: string, config: string, from: string, to: string, top: number, rebalance: number, created: string, ok: boolean, error: string | null, };
