// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SectorCumDto = { t: string, r_p: number, r_alloc: number, r_bench: number, };
