// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectorCumDto } from "./SectorCumDto";

export type SectorAttribDto = { excess_total: number, alloc_pct: number, select_pct: number, cum: Array<SectorCumDto>, };
