// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignalBriefDto = { t: string, 
/**
 * single:目标仓位;portfolio:入选数。
 */
target: number | null, current_pos: number | null, delta: number | null, reason: string | null, leaf: string | null, bars_replayed: bigint | null, 
/**
 * portfolio:目标清单。
 */
targets: Array<[string, number]> | null, n_fresh: bigint | null, };
