// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotDto = { pos: number, entry_price: number | null, bars_held: bigint, nav: number, peak_nav: number, max_drawdown: number, turnover: number, last_increase_date: string | null, max_price_since_entry: number | null, min_price_since_entry: number | null, bars_since_exit: number | null, last_trip_return: number | null, 
/**
 * TripSnapshot 原样 JSON(UI 直接展示,不拆字段)。
 */
trip: unknown, };
