// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagAttribDto = { tag: string, n_picks: number, hit_rate: number, mean_fwd_return: number, };
