// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskProgressDto } from "./TaskProgressDto";

export type TaskInfoDto = { id: string, kind: string, 
/**
 * "running" | "done" | "failed" | "cancelled"
 */
status: string, progress: TaskProgressDto, error: string | null, 
/**
 * 完成结果(JSON 任意形态,manual_run 放 run 摘要)。
 */
result: unknown, };
