// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TradeDto = { entry_t: string, exit_t: string, entry_px: number, exit_px: number, max_abs_pos: number, trip_return: number, bars_held: number, reason: string, 
/**
 * 资金×trip_return——单利近似口径(UI 注明)。
 */
pnl_amount: number, };
