// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TreeInfoDto = { path: string, 
/**
 * load 失败→None + error。
 */
name: string | null, frozen: boolean, error: string | null, };
