// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TwoLegCellDto = { w: number, net_total: number, excess: number, oos_excess: number | null, sharpe: number, max_dd: number, };
