// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TwoLegCellDto } from "./TwoLegCellDto";

export type TwoLegDto = { rows: Array<TwoLegCellDto>, best_w: number, };
