// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UniverseEntryDto } from "./UniverseEntryDto";

export type UniverseInfoDto = { path: string, name: string, 
/**
 * deploy/ 下=true(只读)。
 */
frozen: boolean, entries: Array<UniverseEntryDto>, };
