// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateOutcomeDto } from "./GateOutcomeDto";

export type VerdictDto = { strategy: string, n_symbols: number, certified: boolean, gates: Array<GateOutcomeDto>, failed_gates: Array<string>, };
